/**
 * Created by Administrator on 2017/5/22/022.
 */
var myapp = angular.module('myapp');
myapp.config(['$stateProvider','$locationProvider','$urlRouterProvider',
    function($stateProvider,$locationProvider,$urlRouterProvider){
        //Çå³ýurl Ä©Î²²ÎÊý
        $locationProvider.hashPrefix("");
        $stateProvider.state('register',{
            url:'/register',
            views:{
                'registerView':{
                    templateUrl:'../tpl/register.tpl.html',
                    controller:'registerctr'
                }
           }
    }).state('login',{
            url:'/login',
            views:{
                'loginView':{
                    templateUrl:'../tpl/login.tpl.html',
                    controller:'loginctr'
                }
            }
        }).state('home',{
            url:'/home',
            views:{
                'homeView':{
                    templateUrl:'../tpl/home.tpl.html',
                    controller:'homectr'
                }
            }
        }).state('saicheng',{
            url:'/saicheng',
            views:{
                'saichengView':{
                    templateUrl:'../tpl/saicheng.tpl.html',
                    controller:'saichengctr'
                }
            }
        }).state('details',{
            url:'/details',
            views:{
                'detailsView':{
                    templateUrl:'../tpl/details.tpl.html',
                    controller:'detailsctr'
                }
            }
        }).state('index',{
            url:'/index',
            views:{
                'indexView':{
                    templateUrl:'../tpl/index.tpl.html',
                    controller:'indexctr'
                }
            }
        }).state('designjob',{
           url:'/designjob',
            views:{
                'designjobView':{
                    templateUrl:'../tpl/designjob.tpl.html'
                }
            }
        }).state('matchDetail',{
            url:'/matchDetail',
            views:{
                'matchDetailView':{
                    templateUrl:'../tpl/matchDetail.tpl.html'
                }
            }
        }).state('project',{
            url:'/project',
            views:{
                'projectView':{
                    templateUrl:'../tpl/project.tpl.html',
                    controller:'projectctr'
                }
            }
        }).state('zixunone',{
            url:'/zixunone',
            views:{
                'zixunoneView':{
                    templateUrl:'../tpl/zixun1.tpl.html',
                    controller:'zixunonectr'
                }
            }
        }).state('desCenter',{
            url:'/desCenter',
            views:{
                'desCenterView':{
                    templateUrl:'../tpl/designCenter.tpl.html',
                    controller:'designCenterctr'
                }
            }
        }).state('dss',{
            url:'/dss',
            views:{
                'dssView':{
                    templateUrl:'../tpl/dss.tpl.html',
                    controller:'dssctr'
                }
            }
        }).state('need',{
            url:'/need',
            views:{
                'needView':{
                    templateUrl:'../tpl/need.tpl.html'

                }
            }
        }).state('search',{
            url:'/search',
            views:{
                'searchView':{
                    templateUrl:'../tpl/search.tpl.html'

                }
            }
        }).state('service',{
            url:'/service',
            views:{
                'serviceView':{
                    templateUrl:'../tpl/service.tpl.html',
                    controller:'servicectr'

                }
            }
        });
        $urlRouterProvider.otherwise('index');
    }]);